<?php
/**
 * Copyright © Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/**
 * @var \Amazon\PayV2\Block\Minicart\Button $block
 */
?>

<div id="minicart-amazon-pay-button" class="amazon-button-container-v2" style="display: none;">
    <div class="amazon-divider">
        <span><?= $block->escapeHtml(__('or')) ?></span>
    </div>

    <div class="amazon-button-column">
        <div id="PayWithAmazon-Cart"
             class="amazon-checkout-button"
             data-loaded-at="<?= $block->escapeHtml(time()) // added for force re-rendering ?>"
             data-mage-init='{"Amazon_PayV2/js/amazon-button": {"hideIfUnavailable": ".amazon-button-container-v2"}}'>
        </div>
    </div>
    <div class="checkout-methods-items">
        <div class="amazon-button-column amazon-button-column-tooltip">
            <div class="field-tooltip toggle">
                <span class="field-tooltip-action action-help"
                      data-mage-init='{"dropdown":{"activeClass": "_active"}}'
                      data-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false">
                </span>
                <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true">
                    <?= $block->escapeHtml(__('Are you an Amazon customer? ' .
                        'Pay now with address and payment details stored in your Amazon account.')); ?>
                </div>
            </div>
        </div>
    </div>
</div>
