<?php
/**
 * Copyright © Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
?>
<?php
/**
 * @var \Amazon\Pay\Block\Config $block
 * @var Magento\Csp\Api\InlineUtilInterface $csp
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
**/
?>
<?php if ($block->isEnabled()): ?>
    <?php
    $frontName = $block->getRequest()->getFrontName();
    $pathInfo = $block->getRequest()->getPathInfo();
    $config = $block->getJsonConfig();

    $script = <<<script
    require (['uiRegistry'], function(registry) {
        registry.set('amazonPay', {$config});
    });
    script;
    ?>

    <?php if ($frontName != 'checkout' || (strpos($pathInfo, 'checkout/cart') !== false)): ?>
        <?php
        $script .= <<<script
        require (['Amazon_Pay/js/model/storage'], function(amazonStorage) {
            amazonStorage.clearAmazonCheckout();
        });
        script;
        ?>
    <?php endif; ?>

    <?php if (isset($this->csp)): ?>
        <?= /* @noEscape */ $csp->renderTag('script', [], $script) ?>
    <?php else: ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>
    <?php endif; ?>
<?php endif ?>
