<?php
/**
 * Copyright © Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
?>
<?php
/**
 * @var \Amazon\Pay\Block\ProductPagePaymentLink $block
 */
?>

<div class="amazon-checkout-now" style="display: none;"><?= $block->escapeHtml(__('Checkout now')) ?></div>
<div class="amazon-button-container amazon-button-product-page" style="display: none;">
    <div class="amazon-button-column">
        <div id="PayWithAmazon-Product"
             class="amazon-checkout-button"
             data-mage-init='<?= /* @noEscape */ json_encode([
                 'Amazon_Pay/js/amazon-button' => [
                     'payOnly' => $block->isPayOnly(),
                     'placement' => 'Product',
                     'hideIfUnavailable' => '.amazon-checkout-now,.amazon-button-container',
                 ]
             ]) ?>'>
        </div>
        <a href="javascript:;"
           class="amazon-addtoCart"
           id="amazon-addtoCart-<?= /* @noEscape */ $block->getJsId() ?>"
           data-mage-init='{"amazonPayV2ProductAdd": {}}'>
        </a>
    </div>
    <div class="amazon-button-column amazon-button-column-tooltip">
        <div class="field-tooltip toggle">
    <span class="field-tooltip-action action-help"
          data-bind="mageInit: {'dropdown':{'activeClass': '_active'}}"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
    </span>
            <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true">
                <?= $block->escapeHtml(__('Are you an Amazon customer? ' .
                    'Pay now with address and payment details stored in your Amazon account.')); ?>
            </div>
        </div>
    </div>
</div>
