<?php
/**
 * Copyright © Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/** @var \Magento\Vault\Block\Customer\AccountTokens $block */
$tokens = $block->getPaymentTokens();
?>
<?php if (count($tokens) !== 0): ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="token-list-table">
            <thead>
            <tr>
                <th scope="col" class="col"><?= $block->escapeHtml(__('Accounts')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($tokens as $token): ?>
                <?= /* @noEscape */ $block->renderTokenHtml($token) ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>

