<?php
// @codingStandardsIgnoreFile

/** @var \Amazon\Pay\Block\Customer\VaultTokenRenderer $block */
?>
<tr>
    <td data-th="<?= $block->escapeHtmlAttr(__('Amazon Account')) ?>" class="col account">
        <img src="<?= $block->escapeHtmlAttr($block->getIconUrl()) ?>"
             width="<?= $block->escapeHtmlAttr($block->getIconWidth()) ?>"
             height="<?= $block->escapeHtmlAttr($block->getIconHeight()) ?>"
             alt="<?= $block->escapeHtmlAttr(__('Amazon Logo')) ?>">
    </td>
    <td>
        <?= $block->getExpDate()?>
    </td>
    <td>&nbsp;</td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
        <form class="form"
              action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
              method="post">
            <?= $block->getBlockHtml('formkey') ?>
            <input name="public_hash"
                   value="<?= $block->escapeHtmlAttr($block->getToken()->getPublicHash()) ?>"
                   type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget":{
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $block->escapeHtmlAttr(__('Delete')) ?>",
                            "content": "Are you sure you want to delete the Amazon account ?"
                        }
                    }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
