<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Company $block */
?>
<div class="field password-info">
    <p><?= $block->escapeHtml(__('If you created this account using Amazon Pay, you might not know your site password.')) ?>
        <a href="<?php echo $block->getLink(); ?>"><?= $block->escapeHtml(__('Request a password to change your account password.')); ?></a></p>
</div>