<?php
/**
 * Copyright © Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/* @var \Amazon\Pay\Block\Adminhtml\System\Config\Form\PrivateKeySelector $block */
?>

<button id="private_key_pem_button"><?= __('Upload .pem file') ?></button>
<div><?= __('or') ?></div>
<button id="private_key_text_button"><?= __('Copy & paste') ?></button>
