<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

use Amazon\Pay\Block\Widget\ResetPassword;
use Magento\Framework\Escaper;

/**
 * @var ResetPassword $block
 * @var Escaper $escaper
 */

?>
<div class="field password-info">
    <p>
        <?= $escaper->escapeHtml(__('If you created this account using Amazon Pay,
        you might not know your site password.')) ?><br>
        <?= $escaper->escapeHtml(__('In order to reset your password, please <a href="%1">Sign Out</a>
        and click on “Forgot Your Password?” from the Sign In page', $block->getLink())) ?>
    </p>
</div>
