<?php
/**
 * Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
?>
<?php /** @var \Amazon\Login\Block\Login $block */?>
<div class="block block-amazon-login">
    <div class="block-title">
        <strong id="block-amazon-login-heading" role="heading" aria-level="2">
            <?= $block->escapeHtml(__('Login with Amazon')) ?>
        </strong>
    </div>
    <div class="block-content" aria-labelledby="block-amazon-login-heading">
        <p><?= $block->escapeHtml(__('With Amazon Pay and Login with Amazon, you can easily sign-in and use the ' .
            'shipping and payment information stored in your Amazon account to place an order on this shop. ')) ?>
        </p>
        <div class="actions-toolbar">
            <div class="primary">
                <div class="amazon-button-container">
                    <div class="amazon-button-container__cell">
                        <div id="LoginWithAmazon-<?= /* @noEscape */ $block->getJsId() ?>"
                             class="login-with-amazon"
                             data-mage-init='{"amazonButton": {"buttonType": "LwA"}}'>
                        </div>
                    </div>
                    <div class="amazon-button-container__cell">
                        <div class="field-tooltip toggle">
                            <span class="field-tooltip-action action-help"
                                  data-mage-init='{"dropdown": {"activeClass": "_active"}}'
                                  data-toggle="dropdown"
                                  aria-haspopup="true"
                                  aria-expanded="false">
                            </span>
                            <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true">
                            <?= $block->escapeHtml(__('Securely login into our website using your ' .
                                'existing Amazon details.')); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
